#!/usr/bin/env python

import os
import sys
from string import Template
import subprocess


def main():
    with open('/opt/templates/logstash.template', 'r') as infile, open('/opt/logstash.conf', 'w') as outfile:
        template = Template(infile.read())
        contents = template.substitute(os.environ)
        outfile.write(contents)
        print contents

    return subprocess.call("/opt/logstash/bin/logstash agent -f /opt/logstash.conf -- web".split())


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(0)
